---
- name: "Get reo URL"
  codecommit:
    repo_name: "{{ repo_name }}"
    aws_access_key : "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    region : "{{ region }}"
  register: CodeComm
  delegate_to: localhost

- name: "Create Jenkins Job"
# Create a jenkins job
  jenkins_job:
    config: "{{ lookup('template', 'templates/Jenkins_job.xml.j2') }}"
    name: "TestJob_AWS"
    url: http://localhost:8080
    user: rshylov
    token: 927ae3a57b2793182129944edf421015
