---
- name: Start Setup  ESC
  ecs_cluster:
    aws_access_key : "{{ access_key }}"
    aws_secret_key : "{{ secret_key }}"
    region: "{{ region }}"
    name: "{{ cluster_name }}-2"
    state: present
- ec2:
    aws_access_key : "{{ access_key }}"
    aws_secret_key : "{{ secret_key }}"
    region: "{{ region }}"
    key_name : "{{ project_name }}"
    group : "{{ project_name }}_security_group"
    instance_type : t2.micro
    image : "{{ ami_id }}"
    instance_profile_name: "{{ iam_name }}"
    wait : true
    instance_tags :
      Env: "{{ env }}"
      Name : "{{ ins_name }}-2"
    exact_count: 1
    count_tag:
      Env: "{{ env }}"
      Name: "{{ ins_name }}-2"
    user_data: "#!/bin/bash \n echo ECS_CLUSTER={{cluster_name}}-2 >> /etc/ecs/ecs.config"
  register: ec2

- name: "Wait for SSH to come up"
  local_action: wait_for
                 host={{ item.public_ip }}
                 port=22
                 state=started
  with_items: "{{ ec2.instances }}"


- name: "Add Host to temp hosts"
  add_host:
     hostname: "{{ ins_name }}-ECS-2"
     ansible_host: "{{ item.public_ip }}"
     ansible_port: 22
  with_items: "{{ ec2.instances }}"

- name: "Copy Script"
  template:
     src: script.j2
     dest: /home/{{app_code_user}}/setup_aws_codedeploy.sh
     mode: 0744
  delegate_to: "{{ ins_name }}-ECS-2"
  with_items: "{{ ec2.instances }}"

- name: "Run script"
  shell: /home/{{app_code_user}}/setup_aws_codedeploy.sh
  delegate_to: "{{ ins_name }}-ECS-2"
  with_items: "{{ ec2.instances }}"

- ecs_taskdefinition:
    aws_access_key : "{{ access_key }}"
    aws_secret_key : "{{ secret_key }}"
    region: "{{ region }}"
    containers:
    - name: simple-app-2
      essential: true
      image: "httpd:2.4"
      memory: 300
      cpu: 10
      command:
        - >
          /bin/sh -c "echo '<html> <head> <title>Amazon ECS Instance 2</title> <style>body {margin-top: 40px; background-color: #333;} </style> </head> <body> <div style=color:white;text-align:center> <h1>Amazon ECS Sample 2 </h1> <h2>Congratulations!</h2> </div></body></html>' >  /usr/local/apache2/htdocs/index.html && httpd-foreground"
      entryPoint:
        - sh
        - "-c"
      portMappings:
        - containerPort: 80
          hostPort: 80
    family: "{{ task_name }}-2"
    state: present


- ecs_service:
    aws_access_key : "{{ access_key }}"
    aws_secret_key : "{{ secret_key }}"
    region: "{{ region }}"
    state: present
    cluster: "{{ cluster_name }}-2"
    name: "{{ service_name }}-2"
    task_definition: "{{ task_name }}-2"
    desired_count: 1
    deployment_configuration:
      minimum_healthy_percent: 50
      maximum_percent: 200