---
- name: Start Setup  ESC
  ecs_cluster:
    aws_access_key : "{{ access_key }}"
    aws_secret_key : "{{ secret_key }}"
    region: "{{ region }}"
    name: "{{ cluster_name }}"
    state: present
- ec2:
    aws_access_key : "{{ access_key }}"
    aws_secret_key : "{{ secret_key }}"
    region: "{{ region }}"
    key_name : "{{ project_name }}"
    group : "{{ project_name }}_security_group"
    instance_type : t2.micro
    image : "{{ ami_id }}"
    instance_profile_name: "{{ iam_name }}"
    wait : true
    instance_tags :
      Env: "{{ env }}"
      Name : "{{ ins_name }}"
    exact_count: 1
    count_tag:
      Env: "{{ env }}"
      Name: "{{ ins_name }}"
    user_data: "#!/bin/bash \n echo ECS_CLUSTER={{cluster_name}} >> /etc/ecs/ecs.config"
  register: ec2

- name: "Wait for SSH to come up"
  local_action: wait_for
                 host={{ item.public_ip }}
                 port=22
                 state=started
  with_items: "{{ ec2.instances }}"


- name: "Add Host to temp hosts"
  add_host:
     hostname: "{{ ins_name }}-ECS"
     ansible_host: "{{ item.public_ip }}"
     ansible_port: 22
  with_items: "{{ ec2.instances }}"

- name: "Copy Script"
  template:
     src: script.j2
     dest: /home/{{app_code_user}}/setup_aws_codedeploy.sh
     mode: 0744
  delegate_to: "{{ ins_name }}-ECS"
  with_items: "{{ ec2.instances }}"

- name: "Run script"
  shell: /home/{{app_code_user}}/setup_aws_codedeploy.sh
  delegate_to: "{{ ins_name }}-ECS"
  with_items: "{{ ec2.instances }}"
