---
- include_vars: vault.yml
- name: Start IAM Role
  import_tasks: iam_role.yml
- name: Start Firewall
  import_tasks: firewall.yml
- name: Start KEY SSH
  import_tasks: key_ssh.yml
- name: Start Setup  ESC
  import_tasks: ecs.yml