---
- name: "Create an EC2 key"
  ec2_key:
    aws_access_key : "{{ ec2_access_key }}"
    aws_secret_key : "{{ ec2_secret_key }}"
    name: "{{ project_name }}"
    region: "{{ region }}"
  register: ec2_key


- name: "Save private key"
  copy:
    content: "{{ ec2_key.key.private_key }}"
    dest: "./keys/aws-private.pem"
    mode: 0600
  when: ec2_key.changed