---
 - name : "Provision a set of instances"
   ec2 :
      key_name : "{{ project_name }}"
      group : "{{ project_name }}_security_group"
      instance_type : t2.micro
      aws_access_key : "{{ ec2_access_key }}"
      aws_secret_key : "{{ ec2_secret_key }}"
      image : "{{ ami_id }}"
      region: "{{ region }}"
      wait : true
      instance_tags :
         Env: "{{ env }}"
         Name : "{{ ins_name }}"
         Group: "{{ ec2_group }}"
      exact_count: 1
      count_tag:
         Env: "{{ env }}"
         Name: "{{ ins_name }}-web-01"
   register : ec2

 - name: "Add group to host group"
   vars:
     ll: "[ {{ ec2_group }} ]"
   lineinfile: dest={{ hostpath }}
               line="[{{env}}]"

 - name: "Add the newly created EC2 instance(s) to host group"
   vars:
     ll: "[ {{ ec2_group }} ]"
   lineinfile: dest={{ hostpath }}
               regexp={{ item.public_ip }}
               insertafter="[{{env}}]"
               line="{{ item.public_ip }} {{hoststring}}"
               state=present
   with_items: "{{ ec2.instances }}"

 - name: "Refresh in-memory inventory cache"
   meta: refresh_inventory

 - wait_for: path={{ hostpath }} search_regex={{hoststring}}

 - name: "Wait for SSH to come up"
   local_action: wait_for
                 host={{ item.public_ip }}
                 port=22
                 state=started
   with_items: "{{ ec2.instances }}"