---
 - name : "Provision a set of instances"
   ec2 :
      key_name : "{{ project_name }}"
      group : "{{ project_name }}_security_group"
      instance_type : t2.micro
      aws_access_key : "{{ access_key }}"
      aws_secret_key : "{{ secret_key }}"
      image : "{{ ami_id }}"
      region: "{{ region }}"
      instance_profile_name: "{{ iam_name }}"
      wait : true
      instance_tags :
         Env: "{{ env }}"
         Name : "{{ ins_name }}"
         Group: "{{ ec2_group }}"
      exact_count: 1
      count_tag:
         Env: "{{ env }}"
         Name: "{{ ins_name }}"
   register : ec2

 - name: "Add Host to temp hosts"
   add_host:
     hostname: "{{ ins_name }}-web"
     ansible_host: "{{ item.public_ip }}"
     ansible_port: 22
   with_items: "{{ ec2.instances }}"

 - name: "Wait for SSH to come up"
   local_action: wait_for
                 host={{ item.public_ip }}
                 port=22
                 state=started
   with_items: "{{ ec2.instances }}"
