---
 - name: "Install Apache"
   yum:
     name: httpd
     state: latest
     update_cache: yes
   become: true

 - name: "Make sure a service is running"
   systemd:
     state: started
     name: httpd
   become: true

 - name: "Enable service httpd and ensure it is not masked"
   systemd:
     name: httpd
     enabled: yes
     masked: no
   become: true